title: Programing is funny
author: Lorenzo Méndez Rodríguez
email: lamrodriguez19@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I like the new challenges 

# social links
twitter_username: LorenzoMendezRodriguez # DO NOT include the @ character, or else the build will fail!
github_username:  LorenzoMendezR # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
